### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by fernandoherlo** [klepak/nova-depend-fill#9]
Hi!!
Do you have plans to update the package and make it compatible with Laravel 8?

**Comment by pcorrick** [comment]
I'd also like to use this with Laravel 8, I cloned the package and have the fields showing (as action fields), but my textarea is not populated with the template from my select box.

**Comment by pcorrick** [comment]
I ended up using a different package (https://github.com/epartment/nova-dependency-container) to achieve the result I was looking for.

I have a single Select field, and array of dependent Textarea fields each with a default value set from the Select box values.

**Comment by ahmed-mohammed1** [comment]
@pcorrick @klepak  @daanadriaan
